#! /usr/bin/env bash

YADM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/yadm"
YADM_BOOTSTRAP="${YADM_CONFIG}/bootstraps"
system_type=$(uname -s)

echo "Setup YADM ignores"
yadm gitconfig core.excludesFile ${YADM_CONFIG}/gitignore

#echo "init submodules"
#yadm submodule update --init --recursive

echo "creating directories"
source $YADM_BOOTSTRAP/directories.sh

# Install via home-manager
# echo "installing fonts"
# source $YADM_BOOTSTRAP/fonts.sh

# Install via home-manager
# if [ "$system_type" = "Darwin" ]; then
# 	echo "installing homebrew packages"
# 	source $YADM_BOOTSTRAP/brew.sh
# fi

#source $YADM_BOOTSTRAP/npm.sh
#source $YADM_BOOTSTRAP/pip.sh
#source $YADM_BOOTSTRAP/gem.sh

# Manage via nix-darwin
# if [ "$system_type" = "Darwin" ]; then
# 	echo "configure macos"
# 	source $YADM_BOOTSTRAP/macos.sh
# fi

# source $YADM_BOOTSTRAP/shell.sh
# source $YADM_BOOTSTRAP/terminfo.sh

source $YADM_BOOTSTRAP/home.sh
