#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>

# Determine the platform
if [[ `uname` == 'Linux' ]]; then
  export GNU_USERLAND=1
else
  export LINUX=
fi
if [[ `uname` == 'Darwin' ]]; then
  export OSX=1
else
  export OSX=
fi

# Set default text editor
export VISUAL=vim
export EDITOR="$VISUAL"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Add home bin
if [[ -d "$HOME/.bin/" ]]; then
  export PATH=$HOME/.bin:$PATH
fi
if [[ -d "$HOME/bin/" ]]; then
  export PATH=$HOME/bin:$PATH
fi

# Add locally bins
if [[ -d "/opt/local/bin/" ]]; then
  export PATH=/opt/local/bin:$PATH
fi

# Add locally bins
if [[ -d "/usr/sbin/" ]]; then
  export PATH=$PATH:/usr/sbin:/sbin
fi

# Add locally bins
if [[ -d "/usr/local/" ]]; then
  export PATH=$PATH:/usr/local
fi

# Use Custom Key Map (Map L Ctrl -> Capslock. Map Capslock -> R Menu)
if [ -f $HOME/.Xmodmap ]; then
  /usr/bin/xmodmap $HOME/.Xmodmap
fi

# Add nvm
if [[ -f "$HOME/.nvm/nvm.sh" ]]; then
  export NVM_DIR=$HOME/.nvm
  source $HOME/.nvm/nvm.sh
fi

# Go Lang Setup
if [[ -d "$HOME/Development/go/" ]]; then
  export GOPATH=$HOME/Development/go
  alias go-xbuild='CGO_ENABLED=0 gox -osarch="darwin/amd64 linux/amd64 linux/386" && CC="i686-w64-mingw32-gcc" CGO_ENABLED=1 gox -osarch="windows/386"'
fi

if [[ -d "$HOME/Development/go/bin/" ]]; then
  export PATH=$HOME/Development/go/bin:$PATH
fi

if [[ -d "/usr/local/go" ]]; then
  export PATH=$PATH:/usr/local/go/bin
  export GOROOT=/usr/local/go/
fi

# Python
if command -v pyenv-virtualenv-init > /dev/null; then 
  eval "$(pyenv virtualenv-init -)"; 
fi
if which virtualenv > /dev/null; then 
  # pip should only run if there is a virtualenv currently activated
  export PIP_REQUIRE_VIRTUALENV=true
fi

# Ruby
if command -v rbenv > /dev/null; then
  eval "$(rbenv init -)";
fi
# Source RVM
if [[ -s "${HOME}/.rvm/scripts/rvm" ]]; then
  source $HOME/.rvm/scripts/rvm
fi
if [[ -d "${HOME}/.rvm/" ]]; then
  PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
fi

# Vagrant
export VAGRANT_DEFAULT_PROVIDER=virtualbox

# Add gcloud
if [[ -d "$HOME/google-cloud-sdk" ]]; then
  export PATH=$HOME/google-cloud-sdk/bin:$PATH
  # The next line enables bash completion for gcloud.
  source "$HOME/google-cloud-sdk/completion.zsh.inc"
  # The next line enables shell command completion for gcloud.
  source "$HOME/google-cloud-sdk/path.zsh.inc"
fi

# JumpCloud Go Directory
if [[ -d "$HOME/Development/go/src/github.com/TheJumpCloud" ]]; then
  alias -g gojc=$HOME/Development/go/src/github.com/TheJumpCloud
fi
# Increase the maximum open files. This is useful for filewatcher programs (such as node-dev)
#ulimit -n 10000

## Aliases ##
#alias myip="ifconfig | grep '^[a-z0-1]*:' | cut '-d:' -f1 | xargs -I {} ipconfig getifaddr {}"
alias myip="curl https://icanhazip.com"
alias weather="~/dotfiles/ansiweather/ansiweather"
alias reload-zsh-config='source ~/.zshrc'
alias gen-strong-sshkey='ssh-keygen -t rsa -b 4096 -C "$(whoami)@$(hostname)-$(date -I)"'
alias vagrant-ansible-playbook='ansible-playbook -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory --private-key=.vagrant/machines/default/virtualbox/private_key -u vagrant'
# Could be a git alias, but it had trouble finding pbcopy
alias git-hash='git rev-parse HEAD && git rev-parse HEAD | pbcopy'

# Heroku Fight
alias heroku='/usr/local/heroku/bin/heroku'

# Manual Autocorrect Overrides
alias subl='nocorrect subl'

#Jumpcloud Specific Aliases
alias fetch-agent-staging='scp -r mike@staging.jumpcloud.com:/opt/provisioning-server/files/* ~/Development/SI/agent-files/'
alias rsync-agent-staging='rsync -avz --progress mike@staging.jumpcloud.com:/opt/provisioning-server/files/ ~/Development/SI/agent-files/'
alias rsync-agent-test='rsync -avz --progress mike@test.jumpcloud.com:/opt/provisioning-server/files/ ~/Development/SI/agent-files/'
alias load-int-fixture='mongorestore -db SI /home/mike/Development/SI/test/webui/integration/fixture/SI-integration'
alias load-alarm-int-fixture='mongorestore -db SI /home/mike/Development/SI/test/webui/integration/fixture/alarms/SI-integration'
alias load-personal-fixture='mongorestore -db SI /home/mike/Development/mongodumps/personal/SI'
alias restart-ramdb='/home/mike/Development/SI/bin/mongod-ramdb-linux stop;/home/mike/Development/SI/bin/mongod-ramdb-linux start'
alias reload-ramdb='restart-ramdb;load-int-fixture'
alias reload-personal-ramdb='restart-ramdb;load-personal-fixture'
alias reload-alarm-ramdb='restart-ramdb;load-alarm-int-fixture'
alias drop-test-dbs='mongo /home/mike/Development/SI/bin/queries/drop-SI-Test-dbs.js'

function gcloud-ssh () {
  if [[ -n $1 ]]; then
    gcloud compute ssh --ssh-flag="-A" $1 $2 $3
  else
    echo "Please pass in the instance name"
  fi
}

# Load private environment files
if [ -f $HOME/.private-env ]; then
  source $HOME/.private-env
fi

# Always set the ssh agent in the same place
if [ "$SSH_AUTH_SOCK" != "$HOME/.ssh/ssh_auth_sock" ]; then
  ln -sf "$SSH_AUTH_SOCK" "$HOME/.ssh/ssh_auth_sock"
fi
