#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source RVM
if [[ -s "${HOME}/.rvm/scripts/rvm" ]]; then
  source $HOME/.rvm/scripts/rvm
fi
if [[ -d "${HOME}/.rvm/" ]]; then
  PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
fi

# Add home bin
if [[ -d "$HOME/.bin/" ]]; then
  export PATH=$HOME/.bin:$PATH
fi
if [[ -d "$HOME/bin/" ]]; then
  export PATH=$HOME/bin:$PATH
fi

# Add gcloud
if [[ -d "$HOME/google-cloud-sdk" ]]; then
  export PATH=$HOME/google-cloud-sdk/bin:$PATH
  # The next line enables bash completion for gcloud.
  source '/home/mike/google-cloud-sdk/completion.zsh.inc'
fi

# Add locally bins
if [[ -d "/opt/local/bin/" ]]; then
  export PATH=/opt/local/bin:$PATH
fi

# Add locally bins
if [[ -d "/usr/sbin/" ]]; then
  export PATH=$PATH:/usr/sbin:/sbin
fi

# Add locally bins
if [[ -d "/usr/local/" ]]; then
  export PATH=$PATH:/usr/local
fi

# Use Custom Key Map (Map L Ctrl -> Capslock. Map Capslock -> R Menu)
if [ -f $HOME/.Xmodmap ]; then
  /usr/bin/xmodmap $HOME/.Xmodmap
fi

# Go Lang Setup
if [[ -d "$HOME/Development/go/" ]]; then
  export GOPATH=$HOME/Development/go
fi

if [[ -d "$HOME/Development/go/bin/" ]]; then
  export PATH=$HOME/Development/go/bin:$PATH
fi

# JumpCloud Go Directory
if [[ -d "$HOME/Development/go/src/github.com/TheJumpCloud" ]]; then
  alias -g gojc=$HOME/Development/go/src/github.com/TheJumpCloud
fi
# Increase the maximum open files. This is useful for filewatcher programs (such as node-dev)
#ulimit -n 10000

## Aliases ##
alias myip="ifconfig | grep '^[a-z0-1]*:' | cut '-d:' -f1 | xargs -I {} ipconfig getifaddr {}"
alias weather="~/dotfiles/ansiweather/ansiweather"
alias reload-zsh-config='source ~/.zshrc'

# Heroku Fight
alias heroku='/usr/local/heroku/bin/heroku'

# Manual Autocorrect Overrides
alias subl='nocorrect subl'

#Jumpcloud Specific Aliases
alias fetch-agent-staging='scp -r mike@staging.jumpcloud.com:/opt/provisioning-server/files/* ~/Development/SI/agent-files/'
alias rsync-agent-staging='rsync -avz --progress mike@staging.jumpcloud.com:/opt/provisioning-server/files/ ~/Development/SI/agent-files/'
alias rsync-agent-test='rsync -avz --progress mike@test.jumpcloud.com:/opt/provisioning-server/files/ ~/Development/SI/agent-files/'
alias load-int-fixture='mongorestore -db SI /home/mike/Development/SI/test/webui/integration/fixture/SI-integration'
alias load-alarm-int-fixture='mongorestore -db SI /home/mike/Development/SI/test/webui/integration/fixture/alarms/SI-integration'
alias load-personal-fixture='mongorestore -db SI /home/mike/Development/mongodumps/personal/SI'
alias restart-ramdb='/home/mike/Development/SI/bin/mongod-ramdb-linux stop;/home/mike/Development/SI/bin/mongod-ramdb-linux start'
alias reload-ramdb='restart-ramdb;load-int-fixture'
alias reload-personal-ramdb='restart-ramdb;load-personal-fixture'
alias reload-alarm-ramdb='restart-ramdb;load-alarm-int-fixture'
alias drop-test-dbs='mongo /home/mike/Development/SI/bin/queries/drop-SI-Test-dbs.js'

function gcloud-ssh () {
  if [[ -n $1 ]]; then
    gcloud compute ssh --ssh-flag="-A" --zone us-central1-a $1
  else
    echo "Please pass in the instance name"
  fi
}

