#####
# keybinds
#####
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Shortcut to reload the .tmux.conf
bind r source-file "$HOME/.config/tmux/tmux.conf" \; display "Reloaded"

# Toggle mouse mode
bind-key m set -g mouse \; display-message "Mouse: #{?mouse,ON,OFF}"

# Move Window to the left or right
bind > swap-window -t +1
bind < swap-window -t -1

# Shortcuts to select focused pane based on vim movements
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Shortcuts to resize the pane
bind H resize-pane -L 10
bind J resize-pane -D 10
bind K resize-pane -U 10
bind L resize-pane -R 10

# Session jumping with `fzf`
bind C-! display-popup -E "~/.config/tmux/scripts/session-fzf.sh"

# vi: filetype=tmux
