#####
# options
#####

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Allow tmux clipboard to copy to system clipboard
set -s set-clipboard on

# Set indexs to 1 instead of 0 because 0 is far away on the keyboard
set -g base-index 1
set -g pane-base-index 1

# Renumber windows when a window is closed
set -g renumber-windows on

# time to wait after an escape is input to determine if it is part of a function or meta key sequences.
set -sg escape-time 0

# Turn the mouse on
setw -g mouse on

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Get Mac OS notifications to work from tmux
# https://github.com/julienXX/terminal-notifier/issues/115#issuecomment-104214742
set -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL -l"

# Increase Buffer Size
set -g history-limit 100000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Only restrict size to the smallest terminal if they are active
setw -g aggressive-resize on

# Focus events enabled for terminals that support them
set -g focus-events on

# vi: filetype=tmux
