#####
# theme
#####

set -g @mintt-left-arrow ""
set -g @mintt-right-arrow ""
set -g @mintt-window-separator ""

# Enable smart status-right
set -g @mintt-right true
set -g status-interval 5

run ~/.config/tmux/scripts/theme.tmux

# vi: filetype=tmux
